SampleProject/Controllers/ActionFormController.cs
using SampleProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleProject.Controllers
{
    public class ActionFormController : Controller
    {
        // GET: ActionForm
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetInfo(string EmpName)
        {
            ViewBag.EmpName = "Mr. "+EmpName;
            return View("Index");
        }
        StudentModel st = new StudentModel();
        public ActionResult ShowStudentDetails()
        {
            
            var stdet = st.ShowStudentData();
            return View(stdet);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentDataModel stud)
        {
            var result = st.SaveStudentData(stud);
            if(result>0)
            {
                return RedirectToAction("Index");
            }

            return View();
        }


        public ActionResult Edit(int? id)
        {
           StudentDataModel studentData= st.GetStudentDetail(id);
            return View(studentData);
        }

        [HttpPost]
        public ActionResult Edit(StudentDataModel stud)
        {
            var result = st.EditStudentData(stud);
            if (result > 0)
            {
                return RedirectToAction("ShowStudentDetails");
            }

            return View();
        }


        public ActionResult Delete(int? id)
        {
            StudentDataModel studentData = st.GetStudentDetail(id);
            return View(studentData);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            var result = st.DeleteStudentData(id);
            if (result > 0)
            {
                return RedirectToAction("ShowStudentDetails");
            }

            return View();
        }

        public ActionResult HtmlHelperExample()
        {
            //ViewBag.Students = new SelectList(st.ShowStudentData(), "Sid", "Sname");
            return View();
        }
        [HttpPost]
        public ActionResult HtmlHelper2(string FirstName,string Pwd,string java, string Dotnet,string Gender,string Country,string comments)
        {
            return View();
        }

        public ActionResult StronglyTypeHtmlHelper()
        {
            return View();
        }

        public ActionResult AjaxCallExample()
        {
            return View();
        }
    }
}

SampleProject/Views/ActionForm/AjaxCallExample.cshtml
@{
    ViewBag.Title = "AjaxCallExample";
}

<h2>AjaxCallExample</h2>

SampleProject/Views/ActionForm/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<form action="~/ActionForm/Create" method="post">
    <label>Student Name</label>
    <input type="text" name="Sname" /><br /> 

    <label>Fees</label>
    <input type="number" name="Fees" /><br /><br /> 

     <input type="submit"   value="Save" />

</form>

SampleProject/Views/ActionForm/Delete.cshtml
@model SampleProject.Models.StudentDataModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h2>Are you Sure you want to Delete Record?</h2>
<br />
<span>Sid:</span>@Model.Sid
<br />
<span>Sname:</span>@Model.Sname
<br />
<span>Fees:</span>@Model.Fees
<br />



<form action="~/ActionForm/Delete/@Model.Sid" method="post">
    <input type="submit" name="name" value="DELETE" />
</form>

SampleProject/Views/ActionForm/Edit.cshtml
@model SampleProject.Models.StudentDataModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
 

<form action="~/ActionForm/Edit" method="post">
    <input type="hidden" name="Sid" value="@Model.Sid" />
    <label>Student Name</label>
    <input type="text" name="Sname" value="@Model.Sname" /><br />

    <label>Fees</label>
    <input type="number" name="Fees" value="@Model.Fees" /><br /><br />

    <input type="submit" value="Save" />

</form>

SampleProject/Views/ActionForm/HtmlHelperExample.cshtml
@using SampleProject.Models

@{
    ViewBag.Title = "HtmlHelperExample";
}

<script>
    function funCar() {
        alert("Porsche gl30");
    }
</script>

<h2>HtmlHelperExample</h2>


@using (Html.BeginForm("HtmlHelper2", "ActionForm", FormMethod.Post, new { id = "Form1" }))
{
    <input type="text" name="name" value="" style="color:red" required />


    @Html.TextBox("FirstName", null, new { style = "color:red;", placeholder = "Enter Text Here", @class = "form-control", onclick = "funCar()" })
    <br />
    @Html.Password("Pwd", "xyz")
    <br />
    <span>Java</span>@Html.CheckBox("java", false)
    <span>DotNet</span>@Html.CheckBox("Dotnet", true)
    <br />
    <span>Male</span>@Html.RadioButton("Gender", "Male")
    <span>FeMale</span>@Html.RadioButton("Gender", "FeMale")
    <br />

    @Html.DropDownList("Country", new List<SelectListItem>()
    {
        new SelectListItem{Text="India",Value="1"},
        new SelectListItem{Text="China",Value="2",Selected=true},
        new SelectListItem{Text="America",Value="3"}

    }, "Select Country", new { @class = "form-control" })
    <br />


    @*@Html.DropDownList("Students")*@

    <label>Comments</label> @Html.TextArea("comments", null, 5, 10, null)
    <br />

    <input type="submit" value="submit" class="btn btn-success" />
}

<br />

@myhtmlhelper.MyLabel("I agree with the above information")
<br />

@Html.createUrControl("text", "funCar()")
<br />
@Html.createUrControl("number")
<br />
@Html.createUrControl("date")
<br />
@Html.createUrControl("file")
<br />
@Html.createUrControl("checkbox")
<br />
@Html.createUrControl("radio")
<br />


@helper A(string content)
{
    <label>@content</label>
}
@A("hi this is ali")



@section Section1
{
    Today is Lovely day but i cant see.
}


@*//if you want to create HtmlControls with C# Methods then you can use HtmlHelper

    //two Different type of Html Helper
    //1) loosly type ex:TextBox,Checkbox 2) strongly type ex:TextBoxFor,CheckBoxFor
    //string name property :intialize id="FirstName",name="FirstName" type="text"*@



@*@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <span>File</span>
        <input type="file" id="fileupload" name="fileupload" />
        <input type="submit" value="upload" />
    }
    @ViewBag.msg


      public ActionResult Index()
            {
                return View();
            }
            [HttpPost]
            public ActionResult Index(HttpPostedFileBase fileupload)
            {
                string filename = Path.GetFileName(fileupload.FileName);
                string path = Server.MapPath("~/upload");
                fileupload.SaveAs(Path.Combine(path, filename));
                ViewBag.msg = "uploaded successfully";

                return View();
            }*@

SampleProject/Views/ActionForm/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



<form action="~/ActionForm/GetInfo" method="post">

    <input type="text" name="EmpName" value="asdf" /><br />

    <input type="submit" name="name" value="Submit" />

</form>

<span>EmpName is :</span>@ViewBag.EmpName

 

SampleProject/Views/ActionForm/ShowStudentDetails.cshtml
@model IEnumerable<SampleProject.Models.StudentDataModel>

@{
    ViewBag.Title = "ShowStudentDetails";
}

<h2>ShowStudentDetails</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model =>model.Sid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fees)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fees)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.Sid }) |
            @Html.ActionLink("Details", "Details", new { id = item.Sid }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Sid })
        </td>
    </tr>
}

</table>